name: Test Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run pytest
        run: |
          pip install -r requirements.txt 
          pip install -e .
          pytest